version: '3'

services:
  database:
    container_name: simple-php-app-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_ROOT_PASSWORD: "pwtoor"
      MYSQL_USER: "devuser"
      MYSQL_PASSWORD: "devpass"
    ports:
    - "3306:3306"
    expose:
      - "3306"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    container_name: simple-php-app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
    - "8000:80"
    volumes:
    - "./src:/var/www/html/"
